apiVersion: v1
kind: Service
metadata:
  name: aspnex46
  labels:
    app: aspnex46
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: aspnex46
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnex46
  name: aspnex46
spec:
  selector:
    matchLabels:
      app: aspnex46
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnex46
      name: aspnex46
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: aspnex46
        image: nexus-registry-ci-cd.apps.cluster-bkk-8045.bkk-8045.sandbox697.opentlc.com/aspnetapp:4.6
        imagePullPolicy: IfNotPresent        
      nodeSelector:
        beta.kubernetes.io/os: windows