apiVersion: v1
kind: Service
metadata:
  name: asp47
  labels:
    app: asp47
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: asp47
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asp47
  name: asp47
spec:
  selector:
    matchLabels:
      app: asp47
  replicas: 1
  template:
    metadata:
      labels:
        app: asp47
      name: asp47
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: asp47
        image: chatapazar/aspnetapp:4.7
        imagePullPolicy: IfNotPresent        
      nodeSelector:
        beta.kubernetes.io/os: windows